<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillsTableSeeder extends Seeder
{
    public $skills = [
        'Project Management',
        'Team Leadership',
        'Communication',
        'Problem Solving',
        'Time Management',
        'Adaptability',
        'Collaboration',
        'Creativity',
        'Critical Thinking',
        'Decision Making',
        'Organizational Skills',
        'Strategic Planning',
        'Data Analysis',
        'Marketing',
        'Sales',
        'Customer Service',
        'Research',
        'Writing',
        'Editing',
        'Proofreading',
        'Public Speaking',
        'Negotiation',
        'Conflict Resolution',
        'Interpersonal Skills',
        'Active Listening',
        'Empathy',
        'Emotional Intelligence',
        'Leadership Development',
        'Training and Development',
        'Coaching and Mentoring',
        'Motivating Others',
        'Influencing Others',
        'Persuasion',
        'Networking',
        'Building Relationships',
        'Customer Retention',
        'Account Management',
        'Business Development',
        'Market Research',
        'Product Development',
        'Product Management',
        'Financial Analysis',
        'Budgeting',
        'Forecasting',
        'Risk Management',
        'Quality Control',
        'Process Improvement',
        'Project Coordination',
        'Project Planning',
        'Project Implementation',
        'Project Evaluation',
        'Database Management',
        'Information Management',
        'Information Security',
        'Technical Writing',
        'Web Development',
        'Mobile Development',
        'Software Development',
        'UI/UX Design',
        'Graphic Design',
        'Video Editing',
        'Photography',
        'Animation',
        'Content Creation',
        'Content Strategy',
        'SEO',
        'SEM',
        'Social Media Management',
        'Email Marketing',
        'Event Planning',
        'Event Coordination',
        'Logistics Management',
        'Supply Chain Management',
        'Inventory Management',
        'Procurement',
        'Vendor Management',
        'Contract Management',
        'Legal Research',
        'Legal Writing',
        'Intellectual Property',
        'Human Resources',
        'Recruiting',
        'Talent Management',
        'Performance Management',
        'Compensation and Benefits',
        'Employee Relations',
        'Workforce Planning',
        'Payroll Management',
        'Accounting',
        'Bookkeeping',
        'Tax Preparation',
        'Auditing',
        'Financial Reporting',
        'Investment Analysis',
        'Asset Management',
        'Real Estate',
        'Architecture',
        'Civil Engineering',
        'Mechanical Engineering',
        'Electrical Engineering',
        'Chemical Engineering',
        'Environmental Engineering',
        'Health and Safety',
        'Quality Assurance',
        'Regulatory Compliance',
        'Project Estimation',
        'Project Scheduling',
        'Construction Management',
        'WordPress',
        'Microsoft',
        'Office',
        'Adobe',
        'Photoshop',
        'Adobe Illustrator',
        'Adobe Indesign',
        'Interface Design',
        'Information Technology (IT)',
        'Web Design',
        'HTML',
        'CSS',
        'jQuery',
        'Bootstrap Framework',
        'Testing',
        'Animation',
        'Human Resources (HR)',
        'Recruitment',
        'Interviews',
        'Employment Law',
        'IT/Software Development',
        'Marketing/PR/Advertising',
        'Project/Program Management',
        'Startup',
        'magento',
        'HTML5',
        'CSS3',
        'PostgreSQL',
        'GitPlus',
        'Angular',
        'TypeScript',
        'React',
        'Computer Science',
        'Software Engineering',
        'Python',
        'Linux',
        'Diango',
        'REST',
        'Shell Scripting',
        'Software Technologies',
        'API'
    ];


    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->skills as $skill) {
            DB::table('skills')->insert([
                'name' => $skill,
            ]);
        }
    }
}
